a = int(input("Digite o primeiro valor: "))
b = int(input("Digite o primeiro valor: "))
c = int(input("Digite o primeiro valor: "))
d = int(input("Digite o primeiro valor: "))

print('A soma de A e B é {}'.format((a + b)))
print('A multiplicação de A e B é {}'.format((a * b)))
print('A Soma de A e C é {}'.format((a + c)))
print('A multiplicação de A e C é {}'.format((a * c)))
print('A soma de A e D é {}'.format((a + d)))
print('A multiplicação de A e D é {}'.format((a * d)))
print('A soma de B e C é {}'.format((b + c)))
print('A multiplicação de B e C é {}'.format((b * c)))
print('A soma de B e D é {}'.format((b + d)))
print('A multiplicação de B e D é {}'.format((b * d)))
print('A soma de C e D é {}'.format((c + d)))
print('A multiplicação de C e D é {}'.format((c * d)))